version: '3'
services:
  webapp:
    build: .
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - './:/usr/src/app/'
    links:
      - redisdb
  redisdb:
    image: redis:4.0-alpine
    ports:
      - '${REDIS_PORT}:6379'
